[workspace]
members = [
  "apps/desktop/src-tauri",
  "crates/host",
  "crates/protocol",
  "crates/storage",
  "crates/desktop-macos",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"

[profile.dev]
incremental = true

[profile.release]
lto = "thin"
codegen-units = 1
